name: pearl
channels:
  - kne
  - anaconda
  - defaults
dependencies:
  - backcall=0.1.0
  - blas=1.0
  - blosc=1.16.3
  - bzip2=1.0.6
  - ca-certificates=2019.5.15
  - certifi=2018.8.24
  - cffi=1.11.5
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - cython=0.28.5
  - dbus=1.13.2
  - decorator=4.3.0
  - expat=2.2.6
  - fontconfig=2.12.1
  - freetype=2.5.5
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.2
  - icu=54.1
  - intel-openmp=2019.1
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - joblib=0.9.4
  - jpeg=9b
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.14
  - libpng=1.6.35
  - libstdcxx-ng=8.2.0
  - libxcb=1.13
  - libxml2=2.9.4
  - llvmlite=0.20.0
  - lockfile=0.12.2
  - lz4-c=1.8.1.2
  - lzo=2.10
  - mako=1.0.6
  - markupsafe=1.0
  - matplotlib=2.0.2
  - mkl=2018.0.2
  - ninja=1.8.2
  - numba=0.35.0
  - numexpr=2.6.5
  - openssl=1.0.2s
  - parso=0.3.1
  - patchelf=0.9
  - path.py=10.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pybox2d=2.3.1post2
  - pycparser=2.19
  - pygments=2.2.0
  - pyparsing=2.2.1
  - pyqt=5.6.0
  - pytables=3.4.4
  - python=3.5.2
  - python-dateutil=2.6.1
  - pytz=2018.5
  - qt=5.6.2
  - readline=6.2
  - scipy=1.0.1
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.19.12
  - six=1.11.0
  - snappy=1.1.7
  - sqlite=3.13.0
  - tk=8.5.18
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - atari-py==0.1.7
    - bleach==3.1.0
    - box2d-kengz==2.3.3
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==0.5.2
    - colour==0.1.5
    - defusedxml==0.5.0
    - entrypoints==0.3
    - enum34==1.1.6
    - ffmpy==0.2.2
    - future==0.17.1
    - futures==3.1.1
    - gitdb2==2.0.5
    - gitpython==2.1.7
    - glfw==1.7.0
    - gtimer==1.0.0b5
    - gym==0.12.1
    - idna==2.8
    - imageio==2.5.0
    - imageio-ffmpeg==0.3.0
    - ipdb==0.11
    - ipykernel==5.1.0
    - ipywidgets==7.4.2
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - lxml==4.4.1
    - mistune==0.8.4
    - moviepy==1.0.0
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - notebook==5.7.4
    - numpy==1.18.0
    - pandas==0.23.4
    - pandocfilters==1.4.2
    - pillow==5.3.0
    - proglog==0.1.9
    - prometheus-client==0.5.0
    - pybullet==2.8.1
    - pyglet==1.3.2
    - pyopengl==3.1.0
    - pyquaternion==0.9.5
    - pyzmq==17.1.2
    - qtconsole==4.4.3
    - requests==2.21.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - smmap2==2.0.5
    - terminado==0.8.1
    - testpath==0.4.2
    - torch==1.0.1
    - torchvision==0.2.2
    - tornado==5.1.1
    - tqdm==4.31.1
    - urllib3==1.24.1
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2

